name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
          - os: ubuntu-latest
            arch: arm64
          - os: macos-latest
            arch: x64
          - os: macos-latest
            arch: arm64
          - os: windows-latest
            arch: x64

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.arch == 'arm64' && matrix.os == 'ubuntu-latest' && 'aarch64-unknown-linux-gnu' || '' }}
        override: true

    - name: Build
      run: cargo build --verbose

    - name: Rename binary
      shell: bash
      run: |
        mkdir -p output
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          cp target/debug/commonkey_extractor.exe output/commonkey_extractor_windows_${{ matrix.arch }}.exe
        elif [ "${{ matrix.os }}" == "macos-latest" ]; then
          cp target/debug/commonkey_extractor output/commonkey_extractor_macos_${{ matrix.arch }}
        else
          cp target/debug/commonkey_extractor output/commonkey_extractor_linux_${{ matrix.arch }}
        fi

    - name: Upload single binary
      uses: actions/upload-artifact@v4
      with:
        name: binary-${{ matrix.os }}-${{ matrix.arch }}
        path: output/*

  package:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download all binaries
      uses: actions/download-artifact@v4
      with:
        path: combined_binaries

    - name: Organize folders
      run: |
        mkdir -p final/x64 final/arm64

        find combined_binaries -type f -name "*x64*" -exec mv {} final/x64/ \;
        find combined_binaries -type f -name "*arm64*" -exec mv {} final/arm64/ \;

    - name: Create zip
      run: |
        cd final
        zip -r ../commonkey_extractors.zip .
      uses: actions/upload-artifact@v4

    - name: Upload final zip
      uses: actions/upload-artifact@v4
      with:
        path: commonkey_extractors.zip
