name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: ubuntu-latest
            target: x86_64-pc-windows-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Install cross (for Linux ARM & cross targets)
        if: runner.os == 'Linux'
        run: cargo install cross

      - name: Install cross-compilers for Windows GNU (Linux only)
        if: runner.os == 'Linux' && matrix.target == 'x86_64-pc-windows-gnu'
        run: sudo apt-get update && sudo apt-get install -y mingw-w64

      - name: Download all dependencies
        run: cargo fetch

      - name: Build with cross
        if: runner.os == 'Linux' && matrix.target != 'x86_64-unknown-linux-gnu'
        run: cross build --release --target=${{ matrix.target }}
        shell: bash

      - name: Build native
        if: runner.os != 'Linux' || matrix.target == 'x86_64-unknown-linux-gnu'
        run: cargo build --release --target=${{ matrix.target }}      

      - name: Run tests (native only)
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: cargo test

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-binary
          path: |
            target/${{ matrix.target }}/release/commonkey_extractor${{ matrix.target == 'x86_64-pc-windows-gnu' || matrix.target == 'x86_64-pc-windows-msvc' && '.exe' || '' }}
